import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layouts/Navbar";
import Footer from "./components/layouts/Footer";

const poppins=Poppins(
  {
    weight: ["400", "500", "600", "800"],
  }
)

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <header className="py-2 md:w-11/12 mx-auto ">
          <Navbar/>
        </header>
        <main className="py-2 md:w-11/12 mx-auto ">
        {children}
        </main>
        <footer className="py-2 md:w-11/12 mx-auto ">
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
